### ISSUE TITLE
How to display keyboard?

### ISSUE THREAD

**Issue by username1290** [cxplan/CXTouch#11]
Question: How can I display device keyboard while connected?

**Comment by cxplan** [comment]
Click the text component on device using your left button of mouse, then you can input your content by PC keyboard

**Comment by username1290** [comment]
oh sorry, I want to clarify: 
I'd like to have the Android keyboard visible *as well*, so I can capture it in screenshots or when recording videos. 
I've been able to show it once or twice, but don't know how to keep displaying it when it's connected.

**Comment by cxplan** [comment]
Find the app (CXTouch), open it, and then click the left-upper button, the input method panel will be shown.

**Comment by username1290** [comment]
Input method! you're right, thanks!
