### ISSUE TITLE
Cannot bind listener: cannot bind to 127.0.0.1:30000

### ISSUE THREAD

**Issue by joabsantos** [cxplan/CXTouch#12]
On some computers that I have installed CxTouch I came across this error : 

Cannot bind listener: cannot bind to 127.0.0.1:30000: Normally not allowed only one use of each socket address (protocol / network address / port). (10048).

It does not allow me to see the smartphone, although the cx touch apk is installed.

So, any solution for this?

**Comment by cxplan** [comment]
Please check whether the port 30000 is used by other applications, and close it.
